### PR TITLE
Fix fontStyle assignment

### PR DESCRIPTION
**Pull request by ggrossetie**
### Change type

- [x] `bugfix`
- [ ] `improvement`
- [ ] `feature`
- [ ] `api`
- [ ] `other`

### Test plan

1. Create a text
2. Export as SVG
3. Check that `<text>` element has a valid `font-style` attribute value

- [ ] Unit tests
- [ ] End to end tests

### Release notes

- Fixed a bug where font style wasn't correctly exported as SVG

### CODE REVIEW

**Comment by ggrossetie** [comment]
I have read and agree to the Contributor License Agreement.

**Comment by mimecuvalo** [comment]
thx good catch!

**Comment by mimecuvalo** [comment]
ah, @ggrossetie mind fixing up the tests? :)
See: https://github.com/tldraw/tldraw/actions/runs/9958914769/job/27518664346?pr=4195

just a matter of updating snapshots!

**Review by steveruizok — APPROVED** [review]

**Comment by mimecuvalo** [comment]
No worries! Thanks for the patch :)

**Pull request merged**
