### PR TITLE
Fix indicator transform miscalculation

### PR DESCRIPTION
**Pull request by ds300**
Before
image

After
image

follow up to https://github.com/tldraw/tldraw/pull/1836 should fix the caveat raised by @leolorenzoluis #1834 

### Change Type

- [x] `patch` — Bug fix
- [ ] `minor` — New feature
- [ ] `major` — Breaking change
- [ ] `dependencies` — Changes to package dependencies[^1]
- [ ] `documentation` — Changes to the documentation only[^2]
- [ ] `tests` — Changes to any test code only[^2]
- [ ] `internal` — Any other changes that don't affect the published package[^2]
- [ ] I don't know

[^1]: publishes a `patch` release, for devDependencies use `internal`
[^2]: will not publish a new version

### Release Notes

- Fixes indicator transform miscalculation on android and windows

### CODE REVIEW

**Comment by leolorenzoluis** [comment]
@ds300 Why not dvw or dvh instead of px?

**Comment by ds300** [comment]
would that make a difference? I'm not 100% sure what's going on here but it seems like the floating point accuracy of the transform matrix manipulation is related to the ratio between the size of the wrapper and the translation offset distance of it's child svg. Not sure whether the the size units come into play? Also not sure whether 100px is enough for extreme situations, @steveruizok do you have a better understanding of why size matters in this case?

**Comment by leolorenzoluis** [comment]
@ds300 Maybe... I worry on Apple ecosystem that the calculations could be off. I have not tested it, but if users changes their zoom level too (thankfully they're not like MS where they set default zoom to 125-175%) that could affect the 100px ratio. I'm not sure where the matrix manipulation is in the codebase, and like you said I'm not sure either if size even comes into play.

**Comment by BrianHung** [comment]
image

@ds300 Running into this problem with 125% and 175% zoom on Windows 11 Chrome.

**Comment by BrianHung** [comment]
My current working hypothesis is that `window.devicePixelRatio * width` should be a integer to avoid pixel aliasing.

**Pull request merged**
