### PR TITLE
Fix: Persist app settings on creating new project or reloading the app

### PR DESCRIPTION
**Pull request by nimeshnayaju**
This PR fixes  the issue raised here: #482 , where app settings wouldn't persist on creating a new project or reloading the app.

### CODE REVIEW

**Comment by nimeshnayaju** [comment]
@steveruizok Just realized that the fix doesn't account for multiplayer rooms. I think it may be because we do not pass in an `id` props to the Tldraw component if it's an multiplayer editor, so the following check fails and we end up with the default state:

https://github.com/tldraw/tldraw/blob/main/packages/tldraw/src/state/StateManager/StateManager.ts#L77-L100

**Comment by steveruizok** [comment]
Good point. Should we split the settings into its own keyval store?

**Comment by nimeshnayaju** [comment]
We could do that. Should we store the settings in `IndexedDB` too or opt for simpler client side storage like `localStorage`?

**Comment by steveruizok** [comment]
Either would work! LocalStorage could be easier as it's syncronous.

**Comment by nimeshnayaju** [comment]
Closing this for now because the issue seems to be fixed.

**Pull request closed without merging**
