### PR TITLE
Improve the Text Layout of copySVG

### PR DESCRIPTION
**Pull request by seflless**
The copySVG function is what is called when doing "Copy as SVG" or exporting SVG. Currently the generated SVG's text layout does not match the Tldraw editor's. This PR is a first pass on improving text layout in these cases. 

[Preview deployment is here for those who want to test it](https://tldraw-g0jij7hrq-tldraw.vercel.app/)

Here are some examples of things that aren't working currently.
 - Drop shadows don't work when pasting into Figma (lack of svg filter support it seems)
 - Arrow labels don't work when pasting into Figma (lack of svg filter support it seems)
 - Custom fonts don't work in any SVG previewing Github does (descriptions, comments, SVG file preview, etc)
   - A potential solution of inline fonts has been prototyped, but needs to be discussed more
   - Adding support for subsetting the font to only include the content of the SVG would be ideal
   - If we don't do this, should we try to add fallback fonts like Comic Sans (Amelia from Github Next's joke) for Caveat Brush?
 - Stickies with textAligns of `justify` don't work, svg doesn't have a concept of width for text elements so justify just gets treated as `left`.
 - We shouldn't include references to fonts that aren't used in any of the elements.
 - Text element vertical offsetting is hacky, and with increasingly large scale factors get more and more incorrectly offset.
 - There are some files that are changed in this PR that we didn't touch, looks like prettier wasn't applied to files we merged from main. Not sure how unprettified files ended up in main. Maybe merging with latest on main will make this go away from the diff
 - The generated SVG has fixed padding added around it. I think it should be shrink wrapped to any visual content instead 
 - Need to double check that code pulled in for font loading/subsetting doesn't significantly increase bundle sizes.
- Need to audit code to make we handle strings correctly. Unicode, multi-language: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/codePointAt

## Tldraw Editor
Screen Shot 2022-02-17 at 3 57 42 PM

## Resultant SVG
Screen Shot 2022-02-17 at 3 57 57 PM

### CODE REVIEW

**Comment by seflless** [comment]
Taking a look at other apps. Excalidraw works well so far.

**In Excalidraw**
Screen Shot 2022-02-04 at 1 29 02 PM


**Exported SVG**
excalidraw-test

**Comment by seflless** [comment]
Here are some links/notes into Excalidraw's implementation for reference:
 - [renderSceneToSvg](https://github.com/excalidraw/excalidraw/blob/163ad1f4c463e14f0e5faadc7c8e84fee1e48c02/src/renderer/renderScene.ts#L808)
 - [renderElementToSvg](https://github.com/excalidraw/excalidraw/blob/163ad1f4c463e14f0e5faadc7c8e84fee1e48c02/src/renderer/renderElement.ts#L724) 
 - [if (isTextElement(element)) {](https://github.com/excalidraw/excalidraw/blob/163ad1f4c463e14f0e5faadc7c8e84fee1e48c02/src/renderer/renderElement.ts#L863) (Seems like the heavy lifting is here)
   - Note: Excalidraw's editor uses <canvas> for rendering, so I'm guessing they already do the line breaking themselves, so their line splitting here is taking advantage of that. Use your own judgement though, I'm skimming through the code.

**Comment by seflless** [comment]
Look into html2canvas' implementation and bad news there. It also doesn't support extracting/replicating textarea content layout. It works fine on contenteditable elements though. I don't want to give up and be forced to move to using contenteditable or doing our own text layout just yet.

Notice the textarea (the first bordered box wraps, but it's rasterized one below is a single line)
html2canvas-textarea-vs-contenteditable

Sandbox:
https://codesandbox.io/s/copy-svg-x66ub?file=/src/index.js

**Comment by seflless** [comment]
...but the second paragraph of text, a dom element with the same content and using the contenteditable attribute is perfectly rasterized by html2canvas below.

**Comment by seflless** [comment]
Doing a quick experiment with making a contenteditable replica of the stickynote's textarea has small discrepancies as I recall when I first looked at this for Convey's system. First example, with the content `WWWWWWWW WWWWWW`, notice how the real Stickynote's (right one) first line isn't flush with the right edge, but in the replicated contenteditable version it is flush.
Screen Shot 2022-02-04 at 4 09 32 PM

**Comment by seflless** [comment]
Here's some code I use to dynamacially inject a contenteditable version of a stickynote:
```
window.textLayout = document.createElement('div')
document.body.appendChild(textLayout)
textLayout.style.position = 'absolute'
textLayout.style.zIndex = '10000'
textLayout.style.width = "200px"
textLayout.style.height = "200px"
textLayout.style.boxShadow = 'rgb(0 0 0 / 20%) 2px 3px 12px -2px, rgb(0 0 0 / 16%) 1px 1px 4px, rgb(0 0 0 / 16%) 1px 1px 2px'
textLayout.style.borderRadius = '3px'
textLayout.style.backgroundColor = "rgb(253, 223, 142)"
textLayout.setAttribute('contenteditable', true)
textLayout.innerText = "asdfasdfasdfasdfasdfasdfasdfasdfasdfasdfs adsfasdf aaasdf asdfasdf asdfasdf"
textLayout.style.font = '24px / 1 "Caveat Brush"'
textLayout.style.padding = '16px'
textLayout.style.textAlign = 'center'```

**Comment by seflless** [comment]
Committed a solution for the scaling being ignored. There's a minor issue with the bounding box of the SVG being a bit small and cutting off the text. Made a note of that

Screen Shot 2022-02-04 at 4 38 17 PM

**Comment by seflless** [comment]
Hmmmm, I may have learned a good trick today that makes me more comfortable with going with contenteditable for the measurement shadow element or the stickynote editor itself:
https://twitter.com/DavidKPiano/status/1489585135070625792?s=20&t=EHorn0oRPwf_gXUcO0xfiA

**Comment by seflless** [comment]
There is currently this bizarre behavior in shipped sticky note editor:
https://user-images.githubusercontent.com/1845/152616344-983e2ce5-1978-45c8-922e-b3888a099e2f.mov

To reproduce:
 1. Create a sticky
 2. Type some text on a line but don't make it long enough to wrap
 3. Then fill the rest of the line and then some with many spaces
 4. The text won't scroll past a point and then your cursor becomes totally unrelated to the text you see.

**Comment by seflless** [comment]
Starting a codesandbox to prototype an editor, layout measurement, and/or svg generator.
https://codesandbox.io/s/contenteditable-span-u1cbf?file=/src/index.js

**Comment by seflless** [comment]
Was hoping as a stretch goal that we could make it so if you selected the text of a Stickynote in outputted SVG that you'd get the same exact string back. Looks like no, newlines were ignored in this test.

Source SVG
Screen Shot 2022-02-06 at 9 25 05 AM

What it looks like when on webpage
Screen Shot 2022-02-06 at 9 24 59 AM

What the copy/pasted text comes out like:
Screen Shot 2022-02-06 at 9 25 13 AM

Adding an `\n` in SVG just gets displayed as `\n` in output, but no surprise there. Searching around, I'm not finding any signs that this can be solved. Will pause on that thought for now.
Screen Shot 2022-02-06 at 9 28 53 AM

**Comment by seflless** [comment]
### Making good progress. 

Here's the outputted SVG viewed in Chrome.
Screen Shot 2022-02-06 at 12 58 53 PM

### Pasted into Figma. 
Note, the lack of a drop shadow. From testing other SVG files with drop shadows, I suspect you cant import drop shadows
Screen Shot 2022-02-06 at 1 00 56 PM

### Github Preview
SVG preview on Github has a different issue. Custom fonts aren't working in my tests. Maybe there is a solution still though
*This is what it looks like in a Markdown file (in light mode)*
Screen Shot 2022-02-06 at 1 06 16 PM

*This is what it looks like when navigated directly to the SVG*
Screen Shot 2022-02-06 at 1 04 32 PM

**Comment by seflless** [comment]
Funny fact, the video in the tweet from the *@github* account would have ended badly if they'd actually shown the pasted results. Here's 

### Tldraw Editor View
Screen Shot 2022-02-06 at 1 30 31 PM


### Result (View in Light Mode)
Custom fonts don't work and many things aren't lain out correctly.
Page 1 (6)

**Comment by seflless** [comment]
We could eventually use embedded fonts if we had to. But let's punt for now. It would add ~300K to SVG files which is bigger than the equivalent PNG/JPG, though if getting fancy, you could potentially embed a subset of characters or go to rendering fonts as glyphs.

In general from reading up on it, chasing down edge cases for SVGs sounds like a bad idea. PNGs/etc will always work if we want a file embedding format that is solid in all cases.

Looking at Excalidraw, seems they stopped there too. 

### Excalidraw Editor Version
Screen Shot 2022-02-07 at 5 06 18 PM

### Excalidraw Exported SVG in Github Previews

Screen Shot 2022-02-07 at 5 06 08 PM

**Comment by seflless** [comment]
Fixed the label vertical alignment issue. No longer does this:

Screen Shot 2022-02-17 at 12 50 51 PM

## Resultant SVG
Screen Shot 2022-02-17 at 12 50 38 PM

**Comment by seflless** [comment]
Started a prototype to do the font subsetting ourselves, versus my prototype which leveraged vecta. Work is here:
https://github.com/seflless/svg-font-embedder

**Comment by steveruizok** [comment]
> Following up on above. Should we pursue this?
> 
> * It makes files slightly bigger. In my test above the file only had one font in it, so it'd be 4 x the cost for files with all built in Tldraw fonts.
> * We need to see what infrastructure/libraries are needed to do the base64 generation and ideally subsetting the font down to the file-content's character set.

Yes, let's plan on embedding the fonts. I think we'll need to move from webfonts to serialized fonts anyway—in order to fix issues with webfonts loading on the server.

**Comment by seflless** [comment]
@steveruizok It's the fun way to go, so sounds like a plan.

**Comment by seflless** [comment]
I have a working prototype where I can fetch a font and generate create a new font as a datauri that is a subset font using characters I specify. In the file I'm testing, it had the following characters `' (Scaled2x)\nmizMuLrgTosBykWtCp7+hH'`. Subsetting creates a TTF that is 12KB vs 296KB (24x smaller or 4% of original size). This is the on disk size.

The additional file size from embedding the font was 17KB vs if it was externally referenced. base64 encoding as dataURI is why that's bigger than the 12KB above.

There is still a lot to figure out:
 - How do we package up the font in tldraw/core so we can load it for subsetting and ensure offline works in the VS Code extension or desktop centric Tldraw distributions?
 - Is the library I'm using the best one or good to depend on in the long run. It was last changed in June 2021 for instance.
   - I lean towards using it for now and get to a working solution, then maybe re-evaluating which subsetting solutions are best. 
 - What kind of tests should we write to test subsetting?
   - It'd be nice to be able to do visual diffs comparing the SVG rendered with externally vs embedded font versions
   - Ensuring file sizes are small 
   - Test different language/character sets?

**Comment by seflless** [comment]
The working prototype lives in this simple next.js test app: https://github.com/seflless/next-svg-font-embedded. I'll move the code into this branch now that it's starting to work.

**Comment by seflless** [comment]
Another issue that needs resolving, is figuring out why including fontmanager-core causes the following browser/build console warnings:
```
./node_modules/fonteditor-core/woff2/woff2.js
Critical dependency: the request of a dependency is an expression
```

**Comment by seflless** [comment]
Leaving this link here. Looks like it would be very useful to read. It’s from Iconify’s creator and is about cleaning up and validating SVG: https://docs.iconify.design/articles/cleaning-up-icons/

**Comment by seflless** [comment]
Noticed the *svg-to-excalidraw* channel in the Excalidraw Discord. Might be worth taking a look at that.

**Comment by thatsjonsense** [comment]
Hey @seflless your changes in here are awesome! The `getSvgElement` additions to arrow and triangle are particularly helpful for me, I ran into these exact issues. Have you considered pulling those out into their own PR/is there a reason this got shelved?

**Comment by seflless** [comment]
@thatsjonsense I'm just too busy to take on landing something this complex and it's now months stale. Long term, the approach I took isn't ideal. In particular, the use of the browser's text layout, means exporting is non determinstic, text might wrap different and files will be different depending on who exported it. I don't think that's a good thing for a tool that might want to say generate svg diagrams that you version control, a small change and all of a sudden your files look different or have big diffs.

Additionally, I had started to try to embed fonts, including optimizing out glyphs not used, this also was looking pretty hairy. So basically the scope became too big. 

So definitely, there's a version of this where we just merge the simpler fixes to yeah arrows and such. I'm just trying to prioritize my own projects and work instead of taking on the huge effort to make sure I'm not introducing bugs and such.

The branch now being stale and V2 being the end game, makes me zero motivated to wrap this up. But maybe @steveruizok has a better take on if it's worth getting these improvements into V1 in the interim.

Would love to have someone wrap this up.

**Pull request closed without merging**
