### PR TITLE
serve fonts locally via fontsource

### PR DESCRIPTION
**Pull request by danimo**
With this request, fonts for the text fields in tldraw are no longer sourced from Google servers, but cleanly integrated to be served from the same server as tldraw via the Fontsource project.

We tested this locally with this patch and it works, but tests still fail due to mocking issues. However, this exceeds our knowledge. Help/advise is appreciated.

### CODE REVIEW

**Comment by danimo** [comment]
Please see https://github.com/tldraw/tldraw/pull/1091. Tests need fixing, but the fix has been verified to work manually. Advise is appreciated, esp. on the failing tests.

**Comment by steveruizok** [comment]
Hey, this looks good! The only thing I'm thinking is that SVG exports still use google fonts. Is that acceptable from your end?

**Comment by danimo** [comment]
I am not sure what the alternative would be. I think it depends on the scenario.

* inlining the fonts, i.e. setting `opts.includeFonts` (which is what I would recommend we set in BBB).
* Setting the font, but hoping that the font is in installed on a given machine
* Keep the Google Fonts import

But I think it's good enough for now if BBB can set `includeFonts` to be GDPR compliant.

**Comment by steveruizok** [comment]
Sounds good!

**Comment by bcdrme** [comment]
Be aware that adding fontsource as a dependency makes tldraw incompatible with NextJS 12 : 

image


Related https://github.com/vercel/next.js/issues/19936

**Comment by bcdrme** [comment]
I'm really not sure. 
From what I read, multiple people are considering the issue as an unreasonable limitation from NextJS and some improvements have been made in a beta feature of NextJS 13 but it doesn't seem to work 100% of the time.

Fontsource's documentation gives us more informations however:
https://fontsource.org/docs/guides/nextjs

My understanding is that NextJS forces users to specify what css / fonts they are importing. 
Having said that, a library such as Tldraw shouldn't be modifying global css to import fonts. So the course of action would be to let the user decide what font to import/use in Tldraw ?

**Comment by danimo** [comment]
tldraw has a dedicated list of fonts that represent styles. @steveruizok would need to judge on how to proceed with this. It seems that the import via the google font CDN so far has only shadowed the problem.

**Comment by steveruizok** [comment]
I see. We have a separate method for loading the fonts in the beta which is a bit more naive: leaving them out of the bundle entirely and requiring the app using the library to have them hosted. Easier to override; perhaps easier more compatible with this issue too?

**Comment by danimo** [comment]
if it's documented, this would be fine by me.

**Pull request merged**
