### PR TITLE
feat: change dock position

### PR DESCRIPTION
**Pull request by judicaelandria**
Screen Shot 2022-06-30 at 21 06 16

### CODE REVIEW

**Comment by judicaelandria** [comment]
[770](https://github.com/tldraw/tldraw/issues/770)

**Comment by ali-alhaidary** [comment]
Hi @judicaelandria , good work, but why not at the top as well ?

**Comment by judicaelandria** [comment]
hi @ali-alhaidary that is good idea, let me add that

**Comment by ali-alhaidary** [comment]
@steveruizok ping

**Comment by judicaelandria** [comment]
you don't need to ping him! he will check it when he can

**Comment by steveruizok** [comment]
@judicaelandria This is great! 

image

I'd like to see these menus have their dropdown menu position changed based on where the dock is. IIRC radix has a prop like "side" for which side the menu goes, relative to the trigger button. 

image

The submenu doesn't necessarily have to be vertical, though it could be something else to look at (you've done it with the primary tools, maybe you can re-use that solution?)

**Pull request merged**
