### PR TITLE
Move camera APIs from `editor` to `editor.camera`

### PR DESCRIPTION
**Pull request by SomeHats**
This diff moves all camera controls stuff into a new `CameraManager` class. The old methods are still there, I've just deprecated them. Tagged as galaxy brain for "big refactor", but not actually a backwards compatibility breaking change due to just deprecating the old method.

As part of this, I've added some very basic support for deprecated items to our API reference docs generation.

### Change Type
- [x] `sdk` — Changes the tldraw SDK
- [x] `galaxy brain` — Architectural changes

### CODE REVIEW

**Review by ds300 — APPROVED** [review]
I'm into this. Namespaces are good sometimes and this feels like one of those cases. 👍🏼

**Comment by steveruizok** [comment]
This doesn't seem necessary to me. The design for tldraw is intentional in the editor is a "big flat fat god object", rather than using namespaces for different functionality. (We have one exception, the `user`, which is a sneaky bastard that be eventually refactored out). Even if we did have a camera manager, I would prefer that methods like `zoomToBounds` be on the surface of the editor.

**Review by steveruizok — CHANGES_REQUESTED** [review]
We can extract the improvements to the API markdown / deprecation. Let's talk today about the namespace change.

**Comment by mimecuvalo** [comment]
Namespace change → exposure discussion?
Would be good to chat on it and get on the same page, there's arguments for both sides. There's prbly a lot we can borrow from other engines (i.e. game engines) and how they do/don't namespace things.

**Comment by steveruizok** [comment]
I'm closing this one. There was a miscommunication on my part around extending the camera API. I don't see any strong reason at the moment to change API design direction, so let's put this one to rest.

**Pull request closed without merging**
