### PR TITLE
Added initial webdriver tests

### PR DESCRIPTION
**Pull request by orangemug**
Adds webdriver tests for testing from a users perspective via browser actions. We currently support local test runners for a bunch of actions on desktop `chrome`/`firefox`/`edge`/`safari` on macos.

We also have a browserstack runner which we'll enable in another PR.

### Release Note

- Adds initial webdriver tests

### CODE REVIEW

**Comment by steveruizok** [comment]
Could we rename the BasicExample in apps/webdriver? I don't want it to get confused with the same file in the examples app.

**Comment by orangemug** [comment]
Anything in particular you want to name it?

**Comment by orangemug** [comment]
Is `BasicExampleWebdriver` ok?

**Comment by steveruizok** [comment]
Your call, WebdriverTestApp? Anything but App!

**Comment by orangemug** [comment]
Done @steveruizok are you happy apart from that?

**Comment by SomeHats** [comment]
this is looking great! is the plan to copy across github action etc as a follow-up?

Just before you merge this, it might be worth doing a final copy-paste from tldraw-lite to make sure we have the most up to date set of things here

**Pull request merged**
