### PR TITLE
use the right TLEventHandlers

### PR DESCRIPTION
**Pull request by judicaelandria**
### Change Type

Change the `TLEventHandlers` of `onPointerLeave` to use `onPointerLeave`

- [x] `internal` — Any other changes that don't affect the published package (will not publish a new version)

### Test Plan

I don't think we need to test something here because it's just a small change that doesn't affect anything; just a type IMO

### CODE REVIEW

**Comment by judicaelandria** [comment]
closes https://github.com/tldraw/tldraw/issues/1483

**Comment by steveruizok** [comment]
Looks good! But I'm going to draft this until our CLA is up. (Sorry, coming soon!)

**Comment by judicaelandria** [comment]
> Looks good! But I'm going to draft this until our CLA is up. (Sorry, coming soon!)

yeah, I just saw that `Tldraw` does not accept contribution for now so I closed it but drafting is good idea! thanks

**Comment by judicaelandria** [comment]
I have read and agree to the Contributor License Agreement.

**Pull request merged**
