### PR TITLE
fix: typo in docs

### PR DESCRIPTION
**Pull request by qwertyu-alex**
Describe what your pull request does. If you can, add GIFs or images showing the before and after of your change.

### Change type

- [ ] `bugfix`
- [ ] `improvement`
- [ ] `feature`
- [ ] `api`
- [x] `other`

### Release notes

- Fixed typo in "persistence" in docs

### CODE REVIEW

**Comment by qwertyu-alex** [comment]
I have read and agree to the Contributor License Agreement.

**Comment by mimecuvalo** [comment]
ty!

**Review by steveruizok — APPROVED** [review]

**Comment by steveruizok** [comment]
Thanks!

**Pull request merged**
