### PR TITLE
Use the npm module of browser-fs-access

### PR DESCRIPTION
**Pull request by tomayac**
This new PR supersedes https://github.com/tldraw/tldraw/pull/443. It now works without further changes thanks to improved bundling via microbundle and also all tests pass.

### CODE REVIEW

**Comment by steveruizok** [comment]
Looks good! Thank you @tomayac.

**Comment by tomayac** [comment]
Awesome, glad this could be resolved. Props to @developit and microbundle.

**Comment by kachkaev** [comment]
Thanks for this fix! 👏

When about are you planning to cut `1.10.1`?

**Comment by steveruizok** [comment]
> Oh wow, [1.11.0](https://www.npmjs.com/package/@tldraw/tldraw/v/1.11.0) just went out. Awesome! Thanks for doing this so quickly 👏🚀

Just published!

**Comment by steveruizok** [comment]
Hm, looks like this is breaking our serverless functions.

```
2022-04-29T07:53:46.593Z	251d5153-6cd0-4724-a705-5ab09b7ab878	ERROR	Unhandled Promise Rejection 	{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /var/task/node_modules/browser-fs-access/dist/file-open-32f0dd46.js\nrequire() of ES modules is not supported.\nrequire() of /var/task/node_modules/browser-fs-access/dist/file-open-32f0dd46.js from /var/task/node_modules/browser-fs-access/dist/index.cjs is an ES module file as it is a .js file whose nearest parent package.json contains \"type\": \"module\" which defines all .js files in that package scope as ES modules.\nInstead rename file-open-32f0dd46.js to end in .cjs, change the requiring code to use import(), or remove \"type\": \"module\" from /var/task/node_modules/browser-fs-access/package.json.\n","reason":{"errorType":"Error","errorMessage":"Must use import to load ES Module: /var/task/node_modules/browser-fs-access/dist/file-open-32f0dd46.js\nrequire() of ES modules is not supported.\nrequire() of /var/task/node_modules/browser-fs-access/dist/file-open-32f0dd46.js from /var/task/node_modules/browser-fs-access/dist/index.cjs is an ES module file as it is a .js file whose nearest parent package.json contains \"type\": \"module\" which defines all .js files in that package scope as ES modules.\nInstead rename file-open-32f0dd46.js to end in .cjs, change the requiring code to use import(), or remove \"type\": \"module\" from /var/task/node_modules/browser-fs-access/package.json.\n","code":"ERR_REQUIRE_ESM","stack":["Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /var/task/node_modules/browser-fs-access/dist/file-open-32f0dd46.js","require() of ES modules is not supported.","require() of /var/task/node_modules/browser-fs-access/dist/file-open-32f0dd46.js from /var/task/node_modules/browser-fs-access/dist/index.cjs is an ES module file as it is a .js file whose nearest parent package.json contains \"type\": \"module\" which defines all .js files in that package scope as ES modules.","Instead rename file-open-32f0dd46.js to end in .cjs, change the requiring code to use import(), or remove \"type\": \"module\" from /var/task/node_modules/browser-fs-access/package.json.","","    at new NodeError (internal/errors.js:322:7)","    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1102:13)","    at Module.load (internal/modules/cjs/loader.js:950:32)","    at Function.Module._load (internal/modules/cjs/loader.js:790:12)","    at Module.require (internal/modules/cjs/loader.js:974:19)","    at require (internal/modules/cjs/helpers.js:101:18)","    at /var/task/node_modules/browser-fs-access/dist/index.cjs:1:307"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /var/task/node_modules/browser-fs-access/dist/file-open-32f0dd46.js","require() of ES modules is not supported.","require() of /var/task/node_modules/browser-fs-access/dist/file-open-32f0dd46.js from /var/task/node_modules/browser-fs-access/dist/index.cjs is an ES module file as it is a .js file whose nearest parent package.json contains \"type\": \"module\" which defines all .js files in that package scope as ES modules.","Instead rename file-open-32f0dd46.js to end in .cjs, change the requiring code to use import(), or remove \"type\": \"module\" from /var/task/node_modules/browser-fs-access/package.json.","","    at process.<anonymous> (/var/runtime/index.js:35:15)","    at process.emit (events.js:412:35)","    at process.emit (domain.js:475:12)","    at processPromiseRejections (internal/process/promises.js:245:33)","    at processTicksAndRejections (internal/process/task_queues.js:96:32)"]}
Unknown application error occurred
```

**Comment by steveruizok** [comment]
Reverting until we figure out a fix!

**Comment by steveruizok** [comment]
The world is just not ready for esm 🥲

**Pull request merged**
