### PR TITLE
dev: add test-dev command for easier testing of packages

### PR DESCRIPTION
**Pull request by mimecuvalo**
@si14 you might know a better way to wire this up! lemme know if there's something more clever here.

### Change Type

- [x] `internal` — Any other changes that don't affect the published package[^2]

### Release Notes

- Adds easier testing command for individual packages.

### CODE REVIEW

**Comment by steveruizok** [comment]
@ds300 is this the true lazy way?

**Comment by ds300** [comment]
I think the intention would not be to use this as a lazyrepo task, but rather as something to run while you're in a particular package directory?

Definitely running a bunch of `jest --watch` instances for the whole repo is not ideal and I don't know why anyone would want to do that anyway.

**Comment by steveruizok** [comment]
So not the repo root script? I do `npx jest --watch` a lot whenever I want to kick off a test session in a package.

**Comment by ds300** [comment]
yeah I assume that's what these commands are for. I think this is useful since it is definitely a question that gets asked by new folks.

**Pull request merged**
