### PR TITLE
Update Danish translation

### PR DESCRIPTION
**Pull request by mellson**
Update the Danish translation with all the latest keys from main.json

### Change type
- [x] `other (translation)`

### Release notes

- Updated the Danish translation to include all the latest words from the English original.

### CODE REVIEW

**Comment by mellson** [comment]
I have read and agree to the Contributor License Agreement.

**Comment by mimecuvalo** [comment]
Thanks for your PR @mellson !
We actually handle our localization on an app called [Lokalise](https://tldraw.dev/community/translations).

Can you reach out to me [mime@tldraw.com](mailto:mime@tldraw.com) with your email address? I will add you to the project so that you can make the changes there. Thank you!

**Comment by mellson** [comment]
> [mime@tldraw.com](mailto:mime@tldraw.com)

Yes, I just sent you an email. Thanks for the info; I hadn't noticed the change since I did the last translation update.

But it's great that you're now using Lokalise; that stops me from having to use my little script to automatically add the missing keys 😅

**Comment by steveruizok** [comment]
Ok, closing this PR and we'll pull those changes in from Lokalise. Thank you @mellson !

**Pull request closed without merging**
