### PR TITLE
Add norwegian translation

### PR DESCRIPTION
**Pull request by sifferhans**
- add norwegian translation

### CODE REVIEW

**Comment by ali-alhaidary** [comment]
Hi @steveruizok 
usually languages are put in an alphabetical order to be found easily in the menu. And, it should be main_sub in file naming.

**Comment by steveruizok** [comment]
Thanks @sifferhans! @ali-alhaidary at the risk of being a little imperialist, let's leave English as the first item in the array and sort alphabetically from there.

**Comment by ali-alhaidary** [comment]
> Thanks @sifferhans! @ali-alhaidary at the risk of being a little imperialist, let's leave English as the first item in the array and sort alphabetically from there.

Sure @steveruizok , no problem, but source language is usually called 'main.json', in which in this case is in English that all missing translated keys will default to, and 'en.json' is a duplicate of main.json in this case that is put in proper alphabetical order.

**Comment by steveruizok** [comment]
> > Thanks @sifferhans! @ali-alhaidary at the risk of being a little imperialist, let's leave English as the first item in the array and sort alphabetically from there.
> 
> Sure @steveruizok , no problem, but source language is usually called 'main.json', in which in this case is in English that all missing translated keys will default to, and 'en.json' is a duplicate of main.json in this case that is put in proper alphabetical order.

Sorry, updated my post just before you replied. 

Makes sense! I'll change en.json to main.json.

**Pull request merged**
