### PR TITLE
Make some missing tsdocs appear on the docs site

### PR DESCRIPTION
**Pull request by TodePond**
🚨 Note 🚨
This PR has changed! See my [newer comment](https://github.com/tldraw/tldraw/pull/1706#issuecomment-1623451709) for what the PR does now.
This description is kept here to show the original intention of the PR.

---

This PR fixes the tsdocs formatting of `TldrawEditorProps`, so that they appears on the docs site.

We have docs already written, but they weren't appearing. There are probably others like this too.

image

### Change Type

- [x] `documentation` — Changes to the documentation only[^2]

[^1]: publishes a `patch` release, for devDependencies use `internal`
[^2]: will not publish a new version

### Test Plan

1. Navigate to `/gen/editor/TldrawEditorProps`
2. Make sure that that the parameters are listed out with descriptions.

- [ ] Unit Tests
- [ ] End to end tests

### Release Notes

- Docs: Fixed some missing docs for the TldrawEditor component.

### CODE REVIEW

**Comment by TodePond** [comment]
> i wonder if instead of changing how this is written we should fix the docs generation to support cases like this a bit better. It's a bit weird to have to use `@param` and have a "parameters" header for stuff that aren't really parameters at all

Yeah actually I agree, this is a bit of a reach. I'll change approach here

**Comment by TodePond** [comment]
Hey @SomeHats I tried a different approach. I guess it's a limitation of API Extractor that it doesn't manage to sneakily show comments on properties of types (https://github.com/microsoft/rushstack/issues/3002). To be fair, that would be a lot harder. There seem to be some semi-abandoned PRs fixing it though (https://github.com/microsoft/rushstack/pull/3003) (https://github.com/microsoft/rushstack/pull/3289).

In the meantime, maybe we could get around it by pulling out some properties into an interface instead. I've done that in this PR now. What do you think @SomeHats ?

image

**Comment by steveruizok** [comment]
looks good to me!

**Review by steveruizok — APPROVED** [review]

**Comment by steveruizok** [comment]
Alex is off today, want to merge? The "how to document parameters that take objects" question can be left open.

**Pull request merged**
