### PR TITLE
refactor: Keep hook function convention the same

### PR DESCRIPTION
**Pull request by Lennon57**
I standardized the definition of the `useEditor hook` by changing it from an `arrow function` to a `regular function`, in line with other editor-related hooks.

### Change Type

- [ ] `patch` — Bug fix
- [ ] `minor` — New feature
- [ ] `major` — Breaking change
- [ ] `dependencies` — Changes to package dependencies[^1]
- [ ] `documentation` — Changes to the documentation only[^2]
- [ ] `tests` — Changes to any test code only[^2]
- [x] `internal` — Any other changes that don't affect the published package[^2]
- [ ] I don't know

[^1]: publishes a `patch` release, for devDependencies use `internal`
[^2]: will not publish a new version

### Test Plan

1. Add a step-by-step description of how to test your PR here.
2.

- [x] Unit Tests
- [x] End to end tests

### Release Notes

- Add a brief release note for your PR here.

### CODE REVIEW

**Comment by Lennon57** [comment]
> Hey, thanks for your pull request! Before we can merge your PR, you will need to sign our [Contributor License Agreement](https://tldraw.notion.site/Contributor-License-Agreement-4d529dd5e4b3438b90cdf2a2f9d7e7e6?pvs=4) by posting a comment that reads:
> 
> > I have read and agree to the Contributor License Agreement.

/huppy check cla

**Comment by Lennon57** [comment]
I have read and agree to the Contributor License Agreement.

**Review by steveruizok — APPROVED** [review]

**Comment by steveruizok** [comment]
Sure, this would help with how the function gets classified in the documentation.

**Pull request merged**
