### PR TITLE
feature(electron): introduce tldraw electron

### PR DESCRIPTION
**Pull request by judicaelandria**
https://user-images.githubusercontent.com/46365844/155791195-b03753f7-d826-4608-92e8-75f985ac0a3d.mp4

# Electron Tldraw

This a desktop version of Tldraw that uses BrowserView (like figma)

### CODE REVIEW

**Comment by steveruizok** [comment]
This is fantastic work @judicaelandria! I'm not sure what the purpose is of downloading an image from unsplash as part of the launch process. It seems like a way to delay opening the window?

**Comment by steveruizok** [comment]
Hm, I'm not sure how the menu is supposed to communicate with the BrowserView. And I'm not sure I like that this approach won't work offline (which is one of the better arguments for a desktop app).

**Comment by judicaelandria** [comment]
> This is fantastic work @judicaelandria! I'm not sure what the purpose is of downloading an image from unsplash as part of the launch process. It seems like a way to delay opening the window?

yes it's a way to delay opening the endpoint url not the window

**Comment by judicaelandria** [comment]
> Hm, I'm not sure how the menu is supposed to communicate with the BrowserView; I think we'd need to build an endpoint on the www for that. And I'm not sure I like that this approach won't work offline (which is one of the better arguments for a desktop app).

got your point but BrowserView is like webview but more performant, so everything on web should work on that too, I tried all the menu and it's working. Yes with that loading it's not going to work offline, need a internet connection first then when the website is charged they can work offline
But i'm not sure, is tldraw working offline?

**Comment by steveruizok** [comment]
tldraw should be able to work offline, yes. Our VSCode extension works offline, for example. The only default web-content is the web fonts, though we should consider adding those as local files for this type of application.

**Comment by judicaelandria** [comment]
> tldraw should be able to work offline, yes. Our VSCode extension works offline, for example. The only default web-content is the web fonts, though we should consider adding those as local files for this type of application.

okay I'll fix that and remove the loading with image :D

**Comment by soulsam480** [comment]
Where can I download it
plsss

**Comment by judicaelandria** [comment]
> Where can I download it plsss

Hey @soulsam480, thanks for your interest! we're working on that and we'll keep you updated

**Pull request closed without merging**
