### PR TITLE
Added exporting of shapes and pages as images

### LINKED ISSUE #363: [feature] Copy/Share as PNG
An option to copy/share the selection or the canvas as PNG would be super helpful. 
Currently, I get by with taking screenshots and cropping them, but the cropping step can be bypassed altogether with this option.

Additionally, there could be an option in the menu to export the entire canvas as PNG, however, due to the infinite nature of the canvas, there might be certain limitations that'd need to be put in place for the size of the exported image.

### PR DESCRIPTION
**Pull request by FarazzShaikh**
## Added exporting of shapes and pages as images

Closes #363 #450 #70 

## Adds:
- `TldrawApp#patchAssets`: Patches asset table for the current document 
    - Quite crude at the moment
- `TldrawApp#exportSelectedShapesAs`: Exports selected shapes with the given format (PNG, JPG or WEBP)
    - POST request `www/export` with the following:
        - `shapes`: Array of `TDShape` objects.
        - `assets`: of type `TDAssets`. Just the current Asset table as we need it to populate assets on the server. 
        - `type`: File type of export from the `TDExportTypes` enum.
    - On the server: 
       - Launch headless chrome
       - Load `https://www.tldraw.com/?exportMode`
       - Get `TldrawApp` instance from `window` object
       - Patch asset table of headless instance with `request#assets` using `TldrawApp#patchAssets`
       - Create all shapes in `request#shapes` using `TldrawApp#createShapes`
       - Zoom camera to fit selected shapes using `TldrawApp#zoomToFit`
       - Unselect all shapes in headless instance using `TldrawApp#selectNone`
       - Grab screenshot as blob of headless browser in specified format using `puppeteer.Page#screenshot`
       - Send Blob as response
    - Receive Blob
    - Initiate a download of the Blob.
- `TldrawApp#exportAllShapesAs` Exports all shapes in a page as a given format
    - Save previous selected shape IDs
    - Select all shapes using `TldrawApp#selectAll`
    - Call `TldrawApp#exportSelectedShapesAs`
    - Restore previous selected shapes

## Changes
- Added `exportMode` URL param to  `www/index.tsx`. When present, UI will be hidden. An alternative is to introduce a new function `TldrawApp#toggleUI` but this could get messy so I left it out of this PR.

## Notes:
- Currently, video shapes are **excluded** from the export. This is because Next by default, limits the size of request bodies to 1MB. The base64 asset table entry for video elements is far too big. We can re enable it in one of two ways:
    - When we begin using bucket storage
    - Grab the current frame of the playing video, encode it as base64 and use that instead. I will give this a go.

PS: To trigger the export: 
- Select some shapes
- Right click
- Export

### CODE REVIEW

**Comment by FarazzShaikh** [comment]
Sidenote: I don’t think it will work in the deploy preview, the endpoints are hard coded currently

**Comment by FarazzShaikh** [comment]
@steveruizok

**Comment by steveruizok** [comment]
This is excellent work! 

I had a quick run through this morning and exports had a pretty high error rate, though I couldn't identify what was causing the error.

Regarding video, if you do go that route then let's use it for SVG copy and paste too.

Given that the behavior here could also be incorporated into the VSCode extension or electron app for "offline" use, it might make sense for the export logic to be distributed separately as its own package.

**Comment by FarazzShaikh** [comment]
Thank you! 

If you could share the particular projects examples that were causing errors then I can look into them. 

As for the video solution, it’s a bit experimental, if it works reliably then yes I will break it off into its own package that can be published under the TLDraw namespace

**Comment by FarazzShaikh** [comment]
@steveruizok I have added in video serialization to SVG copy and image exports. Currently is a very small function `TldrawApp#serializeVideo` not sure if this one function calls for its own package? If so then no problem, I can pull it out into one.

**Comment by FarazzShaikh** [comment]
BTW to have automated tests of the export capabilities, we can use image similarity checks like the way ThreeJS tests its examples https://github.com/mrdoob/three.js/blob/dev/test/e2e/puppeteer.js

This will give us a more quantifiable error rate. For me, everything works 100% of the time locally

**Comment by steveruizok** [comment]
Finally had a chance to dig into this, great work @FarazzShaikh! 

I've made a few changes:

1. I was getting bugs when we were trying to access the app before it had mounted, so I've added a pause on the server if necessary to let it load.
4. I've set the puppeteer browser's viewport to be 2x the dimensions of the selected shapes.
2. I've extracted the export functionality into an `onExport` callback, so that developers can implement their own endpoint.
3. I've made the menu items dependent on the presence of that callback.

**Comment by steveruizok** [comment]
I'd like to also include SVG export, since we have that functionality already from `copySvg`. We can track that as a separate issue but it should be pretty straightforward.

**Comment by FarazzShaikh** [comment]
Thanks! Correct me if I’m wrong but can’t we just write the result or `copySVG` to a file? This wouldn’t even require the server. 

Should I give this a shot in this PR or make a new one referencing the new issue you will create?

**Comment by steveruizok** [comment]
Give it a shot!

**Comment by FarazzShaikh** [comment]
Yay! I’m glad the video serialization works so well!

**Comment by steveruizok** [comment]
I'm going to drop the export side to 1x for jpeg/webp and 2x for png, since exporting to png usually suggests an interest in quality.

**Comment by FarazzShaikh** [comment]
Yep that sounds good, maybe we can even have options for the user to select level of quality

**Comment by steveruizok** [comment]
I'm not getting text on my exports, are you? Perhaps we need to load those fonts manually on the server?

**Comment by steveruizok** [comment]
Text shows if I remove `display=block` from the import CSS, though I really would rather not do that as the correct fonts are needed for the renderer to size things correctly.

**Comment by FarazzShaikh** [comment]
Huh that’s quite weird. Why would some CSS block the app form loading the test shapes?

**Comment by steveruizok** [comment]
The webfonts just weren't loading, and since we had display=block, the elements wouldn't display until the fonts arrived. The fonts are necessary because we measure actual text elements in order to get their bounding boxes, and those boxes will be wrong if the fonts aren't loaded yet.

**Comment by FarazzShaikh** [comment]
Ah I see, well I’m glad it’s fixed! 

I will get on SVG exports tomorrow, got a lot on my plate today

**Comment by no-1ne** [comment]
Wow looking forward.

During webm export if this may help https://github.com/StaZhu/fix-webm-meta

**Comment by steveruizok** [comment]
> Wow looking forward.
> 
> During webm export if this may help https://github.com/StaZhu/fix-webm-meta

Cheers. I don't think we'll be exporting video any time soon! (Although perhaps...)

**Comment by FarazzShaikh** [comment]
I’d love to have video, although there are some UX considerations with that. Let’s put that in a new issue

**Comment by FarazzShaikh** [comment]
Done! Added in SVG export (fully offline) with a bonus JSON exports too!

**Comment by no-1ne** [comment]
Can the  exported json be loaded again, if not it would be great to have that capability.

**Comment by FarazzShaikh** [comment]
Haven't tested that but I don’t think that’s in yet. But that’s beyond the scope of this PR. If you could open a new feature request that would be great! 

I think drag-and-drop loading of both JSON and .tldr files would be super cool and straightforward to implement. I can pick it up on the weekend

**Comment by steveruizok** [comment]
Merged! Thanks to @FarazzShaikh for getting this one going!

**Pull request merged**
