### PR TITLE
Try to re-re-migrate to npm module of browser-fs-access

### PR DESCRIPTION
**Pull request by tomayac**
Supersedes https://github.com/tldraw/tldraw/pull/653, incorporating a problem identified in https://github.com/tldraw/tldraw/pull/658.

### CODE REVIEW

**Review by pengx17 — APPROVED** [review]
Great work!

**Comment by tomayac** [comment]
@steveruizok Please see if this still causes the serverless function problem (https://github.com/tldraw/tldraw/pull/653#issuecomment-1113001592). It no longer dynamically `import()`s as in #653, which was a stupid oversight on my part, noticed by @pengx17.

**Comment by tomayac** [comment]
@steveruizok There seems to be a typing problem: 

```
✔ @tldraw/tldraw: src/state/data/filesystem.ts(24,50): error TS2304: Cannot find name 'FileSystemFileHandle'.
```

I'm not super versed with TypeScript, maybe someone else can fix this?

**Comment by tomayac** [comment]
The problem seems to be the following:

- If I do _not_ use the `FileSystemHandle` type exported from `browser-fs-access`, TyepScript uses its own, but this version doesn't have the `FileSystemHandle.queryPermission()` and `FileSystemHandle.requestPermission()` methods yet.
- If I _do_ use the `FileSystemHandle` type exported from `browser-fs-access`, TyeScript doesn't seem to understand that `FileSystemFileHandle` extends `FileSystemHandle`.

I tried using [`@types/wicg-file-system-access`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/wicg-file-system-access/index.d.ts), but then all hell broke loose and nothing worked. Someone more familiar with TypeScript is probably easily capable of fixing this.

**Comment by steveruizok** [comment]
Thanks for sticking with this one. I'll look into the TypeScript issues too.

Maybe we should get someone like @Andarist on browser-fs-access; the lib is certainly worth the attention!

**Comment by Andarist** [comment]
@tomayac could you prepare a branch with this change so I could take a look?
> If I do use the FileSystemHandle type exported from browser-fs-access, TyeScript doesn't seem to understand that FileSystemFileHandle extends FileSystemHandle.

Even though both types (the one exported from `browser-fs-access` and the lib DOM type) are called the same (`FileSysttemFileHandle`), they are not exactly the same for the type system (their identity is different). However, TS is a structural type system and not a nominal one - so I wonder where this problem has manifested for you. It would be worth knowing that to understand the problem and the fix for the issue better

**Comment by tomayac** [comment]
@Andarist Please see the commit https://github.com/tomayac/tldraw/commit/54ef2004762501755c0af328075034a9db431f17 in [tomayac/tldraw/file-system-access](https://github.com/tomayac/tldraw/tree/file-system-access), where the problem manifests:

Screenshot 2022-08-09 at 15 32 55

Thanks for your help in advance!

**Comment by Andarist** [comment]
The reported error is correct here - you can't assign an instance of a superclass to a function that expects an instance of its subclass (u try to pass something less specific as something more specific). 

Perhaps the problem here is that those 2 are typed as `FileSystemHandle` rather than `FileSystemFileHandle`?
1. https://github.com/tomayac/tldraw/blob/54ef2004762501755c0af328075034a9db431f17/packages/tldraw/src/state/TldrawApp.ts#L225
2. https://github.com/tomayac/tldraw/blob/54ef2004762501755c0af328075034a9db431f17/packages/tldraw/src/state/data/filesystem.ts#L27

I don't see in those files any directory-related handling, so I somewhat assume that I'm on a right track here.

**Pull request closed without merging**
