### PR TITLE
translate to korean

### PR DESCRIPTION
**Pull request by nayounsang**
Describe what your pull request does. If you can, add GIFs or images showing the before and after of your change.

### Change type

- [ ] `bugfix`
- [x] `improvement`
- [ ] `feature`
- [ ] `api`
- [x] `other`

### Test plan

- [ ] Unit tests
- [ ] End to end tests

### Release notes
#4474 
I translates keys that have not yet been translated into Korean.
assets/translations/ko-kr.json.
This is part of result.
image

### CODE REVIEW

**Comment by nayounsang** [comment]
I have read and agree to the Contributor License Agreement.

**Comment by nayounsang** [comment]
@mimecuvalo 
I sent an email with nayounsang722@gmail.com

**Comment by mimecuvalo** [comment]
Thank you! You've been invited.

**Comment by nayounsang** [comment]
I finished it in Lokalise.
Is there anything else I need to do for the changes to take effect?

**Comment by TodePond** [comment]
@nayounsang amazing, thank you! I'll trigger a PR from Lokalise now to pull the changes through :)

**Comment by TodePond** [comment]
Merging these changes in this PR: https://github.com/tldraw/tldraw/pull/4498
Thanks again!

**Pull request closed without merging**
