### PR TITLE
add triangle tool

### PR DESCRIPTION
**Pull request by elouiestudent**
This commit adds a triangle tool to the tldraw app. Refer to #303.

https://user-images.githubusercontent.com/37051992/144699203-4c0a2907-294a-4f8a-85ce-bf322fd3fd3a.mov

TODO:
- [x] fix keybindings to include the triangle tool
- [ ] add draw style to the triangle

### CODE REVIEW

**Comment by steveruizok** [comment]
Hey, this is a great start! There were a few things missing (hit tests, pretty complex) so I’m filling in those blanks. 

Thinking more on this, it would be smart to adapt this into a generic “polygon” shape. Regular polygons are very similar to ellipses, actually, with the number of points placed equally along the perimeter of the ellipse. The bounds calculation is different, of course (it would need to use Utils.getBoundsFromPoints), and the transform too (it would be more similar to how we’re doing transforms for the draw shape)

More on how this kind of shape works: https://discord.com/channels/859816885297741824/859816885801713728/914224620180230225

**Comment by elouiestudent** [comment]
Hey @steveruizok, thanks for the review and the additional fixes! 

There are a couple of things that I noticed:
It looks like the binding indicator for the triangle is somewhat off-center.

https://user-images.githubusercontent.com/37051992/144724950-091e3370-34be-4ec9-b3b1-3d4774168e1b.mov

Also, the blue outline indicating selection on the ellipse is no longer on the ellipse but rather around it and outside of the exterior blue highlight rectangle.
Screen Shot 2021-12-04 at 4 03 46 PM

We're not sure how to best proceed with fixing these issues and wanted to bring them to your attention. Thanks again for your guidance and support throughout this process!

**Comment by steveruizok** [comment]
I believe the ellipse issue is unrelated, and has been that way for a few weeks. Needs fixing but maybe not on this PR.

## Binding

After spending some more time with the math, I decided to track down some code for polygon offsetting, which we're now using to "expand" the triangle. We will also be able to use this for other polygons in the future.

image

The shape's expanded bounds are based on these points.

image

If the arrow is inside of the expanded bounds, then we check for a hits against the expanded triangle.

image

And then find the two intersections and anchor point (between the two).

image

And update the arrow so that its handle is placed along the expanded edges. Whew!

## Binding Indicator

For the binding indicator, I've decided to save ourselves some math and use the SVG engine's offsetting for the stroke. This means a tweak to how binding indicators look.

image

I've rolled this out into the other shapes as well.

**Comment by steveruizok** [comment]
Added a fix for the ellipse too. When the shape has a Draw dash style, we add a little randomness to the shape of the ellipse, so the indicator needs to take that into account. We'll do this for the Triangle too, eventually!

**Comment by elouiestudent** [comment]
Thanks for the quick turnaround and for taking the time to explain the math behind your fixes!

**Comment by elouiestudent** [comment]
Hey @steveruizok, is this PR ready to be merged or are there additional changes that need to be made?

**Comment by steveruizok** [comment]
There are a few conflicts that I'll need to resolve. Tomorrow!

**Comment by steveruizok** [comment]
...or tonight, I guess!

**Comment by steveruizok** [comment]
There are some quirks in the polygon offsetting, where a very narrow triangle will become a very tall triangle. This can cause some strange placement with bound arrows. It's not a killer but something to note.

**Pull request merged**
