### PR TITLE
Add Discord link to Menu

### PR DESCRIPTION
**Pull request by dinaco**
[feature] Add Discord link to Menu #309

### CODE REVIEW

**Comment by proful** [comment]
Please change the PR title to make it relevant.

**Comment by dinaco** [comment]
> Please change the PR title to make it relevant.

Done. Thats my first PR ever, so newbie mistake, thanks for the tip.

**Comment by steveruizok** [comment]
Thanks! I'll review in a few minutes but it looks good to me. Congrats on the first PR!

**Comment by steveruizok** [comment]
Thanks again @dinaco!

**Comment by proful** [comment]
Congratulations @dinaco for your first PR

**Pull request merged**
