### PR TITLE
[improvement] faster svg paths

### PR DESCRIPTION
**Pull request by steveruizok**
This PR:
- improves the performance of tldraw by improving the methods we were using to turn freehand points into SVG path data
- bumps perfect-freehand to the latest version

### CODE REVIEW

**Comment by steveruizok** [comment]
See https://github.com/tldraw/tldraw/issues/957. (This PR incorporates @todepond's changes to perfect-freehand, too.)

**Comment by steveruizok** [comment]
Feels a little faster? Hard to tell tbh!

**Comment by TodePond** [comment]
> Feels a little faster? Hard to tell tbh!

I'll measure it! Then we can know for sure.

This is what I have so far:
image

Example 2 is the second function you put in that codepen on twitter - looks quicker already. I'll keep measuring more stuff!

**Comment by TodePond** [comment]
I'll keep posting more findings in the issue: #957

**Pull request merged**
