### PR TITLE
feat: use potpack to pack shapes into a rectangle

### PR DESCRIPTION
**Pull request by pengx17**
Add a new distribute action using https://github.com/mapbox/potpack, which will use each shape bound as the box input to get an optimal rectangle distribution.

However, I am not confident about the positioning of the distribute icon is question which breaks the balance of existing align/distribute icons

image

https://user-images.githubusercontent.com/584378/195132331-ddcbf71d-ff39-48b4-aee6-4311eb071705.mp4

### CODE REVIEW

**Comment by steveruizok** [comment]
Playing around with this in the next version. I think we'll need to exclude bound arrows from the algo, or else they end up taking space but then moving.

**Comment by steveruizok** [comment]
Really nice though!

**Comment by pengx17** [comment]
bound arrows are now excluded in the new implementation

**Comment by pengx17** [comment]
@steveruizok any news on this PR?

**Comment by pengx17** [comment]
@steveruizok I saw this PR and some other PRs to targeting V1 branch were closed without given any reason. Could you please provide more information on why they were closed?

**Comment by TodePond** [comment]
Hey @pengx17, apologies, we're preparing this repo for the open-sourcing of the new tldraw version so we've been closing PRs ahead of that. 
We're going to be moving the original tldraw codebase over to https://github.com/tldraw/tldraw-v1

**Pull request closed without merging**
