### PR TITLE
Adding Arabic Language

### PR DESCRIPTION
**Pull request by ali-alhaidary**

### CODE REVIEW

**Comment by ali-alhaidary** [comment]
@steveruizok

**Comment by ali-alhaidary** [comment]
@judicaelandria

**Comment by judicaelandria** [comment]
thanks! can you verify, there's something wrong, the arabic language is not working

**Comment by ali-alhaidary** [comment]
> thanks! can you verify, there's something wrong, the arabic language is not working

thanks @judicaelandria are there more files involved to update? I do not know how to run my modifications :-)
I followed previous language added that was merged successfully...

**Comment by ali-alhaidary** [comment]
@judicaelandria now working as expected, so many thanks...

**Comment by judicaelandria** [comment]
thank you for adding more languages to tldraw @ali-alhaidary!

**Comment by ali-alhaidary** [comment]
@judicaelandria you are more than welcome, who can merge it ?

**Comment by ali-alhaidary** [comment]
@steveruizok

**Comment by ali-alhaidary** [comment]
@yyyang1996

**Comment by steveruizok** [comment]
Cheers, thanks!

**Pull request merged**
