### PR TITLE
added CAD like behavior like described in issue #555

### PR DESCRIPTION
**Pull request by Leone25**
see https://github.com/tldraw/tldraw/issues/555

hopefully I've done everything right

### CODE REVIEW

**Comment by steveruizok** [comment]
I think we may need to make this into a preference. My bet is that unless folks have opted in, the feature is going to be a miss or feel like a bug; but those people who have opted in will appreciate that it's there. Generally I try to keep the number of "behavioral options" to a minimum—grid being an example exception, and this one, too.

So there's a little more UI to write before we ship this but it's going to get in.

**Comment by steveruizok** [comment]
Looking at this now!

**Comment by steveruizok** [comment]
Ok, made a few changes here:

- removed the colors styles
- renamed / moved the prop
- added a new "dashed" style to the theme object
- added "perfect" dash props to the edges on the "contain-mode" brush

It's doesn't look exactly like CAD but I think it's close enough!

**Comment by Leone25** [comment]
well as it's currently i think it's even more confusing because it goes against common, dashed vs solid line should be reversed as it's the opposite of all CAD software

the color change was implemented as it was often requested on twitter, and dashed vs solid line should be reversed

**Comment by steveruizok** [comment]
I see—so in CAD mode, the dashed line indicates collision rather than contain?

**Comment by Leone25** [comment]
correct

**Comment by steveruizok** [comment]
Ok, let me create a new PR with that change.

**Pull request merged**
