### PR TITLE
docs: keep search endpoints hot on vercel

### PR DESCRIPTION
**Pull request by mimecuvalo**
I was shutting down my DigitalOcean server over the weekend and forgot that I had some cron jobs there to keep the search endpoints "hot". (to avoid the cold boot problem for lambda functions). This brings over those cron jobs. There are two at the same time to make sure it makes more than one instances.

(If there's a better way to do this, I'd love to know btw)

### Change Type

- [ ] `sdk` — Changes the tldraw SDK
- [ ] `dotcom` — Changes the tldraw.com web app
- [x] `docs` — Changes to the documentation, examples, or templates.
- [ ] `vs code` — Changes to the vscode plugin
- [ ] `internal` — Does not affect user-facing stuff

- [x] `bugfix` — Bug fix
- [ ] `feature` — New feature
- [ ] `improvement` — Improving existing features
- [ ] `chore` — Updating dependencies, other boring stuff
- [ ] `galaxy brain` — Architectural changes
- [ ] `tests` — Changes to any test code
- [ ] `tools` — Changes to infrastructure, CI, internal scripts, debugging tools, etc.
- [ ] `dunno` — I don't know

### CODE REVIEW

**Comment by steveruizok** [comment]
Hm, keeping serverless endpoints warm always makes me feel gross. I'd prefer to leave things as they are until we replace with a proper search backend. @SomeHats can I bring you in as tie breaker?

**Comment by mimecuvalo** [comment]
Agreed that it's definitely gross but ¯\_(ツ)_/¯ 
If you don't wanna merge this PR I can also set up a cron job on my personal server just to create this artificial traffic heh :)

**Comment by steveruizok** [comment]
Is it really necessary? The search is takes what, a few seconds to warm up? Not ideal but ok?

**Comment by mimecuvalo** [comment]
> Is it really necessary? The search is takes what, a few seconds to warm up? Not ideal but ok?

I mean, meh, it's not the biggest deal. It's just when traffic is intermittent and you're the person waking up the endpoint it feels extra slow. But happy to close this.

**Pull request closed without merging**
