### PR TITLE
Adding Arabic Language

### PR DESCRIPTION
**Pull request by ali-alhaidary**

### CODE REVIEW

**Comment by judicaelandria** [comment]
hi @ali-alhaidary! thanks for the pr but please can you remove the duplicate pr and just all your pr into just one pr? thanks!

**Comment by ali-alhaidary** [comment]
Thank you @judicaelandria they are all for the same issue, but different files. I do not know how to combine them all in one PR :-)

**Comment by judicaelandria** [comment]
you can push multiple files in one pr! make your changes, push it and create a pr,

**Comment by ali-alhaidary** [comment]
https://github.com/tldraw/tldraw/pull/732

**Pull request closed without merging**
