### PR TITLE
fix: Broken screenshot image link

### PR DESCRIPTION
**Pull request by the-spectator**
fix: Broken screenshot image

Before:
image

After:
image

### CODE REVIEW

**Comment by judicaelandria** [comment]
hi! thanks for the pr, but it's weird tho, I don't see a broken  screenshot on my side (how about you check in again ?)

**Comment by the-spectator** [comment]
Hi @judicaelandria. I rechecked on incognito again, it still looks broken for me. Can you check on this URL https://github.com/tldraw/tldraw/tree/main/packages/tldraw.

**Comment by judicaelandria** [comment]
oh you meant the tldraw package readme, yeah it's broken

**Comment by steveruizok** [comment]
Thank you!

**Comment by the-spectator** [comment]
Thank you for the merge! 🎉

**Pull request merged**
