### PR TITLE
[Translation] add Simplified Chinese translation

### PR DESCRIPTION
**Pull request by yyyang1996**
Add Simplified Chinese translation.

### CODE REVIEW

**Comment by judicaelandria** [comment]
Thanks you for contributing to the translation of tldraw 😄

**Comment by bestony** [comment]
LGTM, as a Chinese Reviewer.

**Comment by yyyang1996** [comment]
> LGTM, as a Chinese Reviewer.

Hi, ByteDancer! I know you!

**Review by steveruizok — COMMENTED** [review]
Amazing!

**Pull request merged**
