### PR TITLE
feat: add new prop to force mobile mode layout

### LINKED ISSUE #1709: [Feature]: Add Flag to Activate Compact Mode UI
### What's the feature?

The compact mode UI, which hides the style menu behind a toggle button next to the toolbar, currently only activates when the window is resized to a small screen size via media queries. However, there are use-cases where it would be beneficial to manually activate the compact mode, regardless of screen size.

I propose the addition of a flag that can be passed to the tldraw instance to manually activate the compact mode UI. This would allow users to switch to compact mode without needing to resize their window. When this flag is set to true, the style menu should mimic the compact mode's behavior on smaller screens by hiding behind a toggle button next to the toolbar.

### Contact Details

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by gabrielchl**
Adds a new prop to force mobile mode layout, similar to how the ?layout=mobile query param works.

An alternative of having the prop accept a breakpoint number was considered, but while that provides more flexibility, it's best if usages of tldraw don't need to know about the internal workings of tldraw. (e.g. someone might use breakpoint 7 to get the "desktop" mode, but that won't be reliable when in the future more breakpoints are added)

licecap-output-1
licecap-output-2

Closes #1709 

### Change Type

- [ ] `patch` — Bug fix
- [x] `minor` — New feature
- [ ] `major` — Breaking change
- [ ] `dependencies` — Changes to package dependencies[^1]
- [ ] `documentation` — Changes to the documentation only[^2]
- [ ] `tests` — Changes to any test code only[^2]
- [ ] `internal` — Any other changes that don't affect the published package[^2]
- [ ] I don't know

[^1]: publishes a `patch` release, for devDependencies use `internal`
[^2]: will not publish a new version

### Test Plan

1. `<Tldraw persistenceKey="tldraw_example" autoFocus forceMobileModeLayout />`
2. notice that the layout stays in mobile mode no matter the width of the screen

- [ ] Unit Tests
- [ ] End to end tests

### Release Notes

- add new prop to force mobile mode layout

### CODE REVIEW

**Comment by steveruizok** [comment]
Hi @gabrielchl, finally coming to this one.

I've pushed some changes to the PR:

I've removed the previous way of doing this (the `?layout=mobile` or `?layout=desktop` url param)

Instead of using `forceMobileLayout`, I've added `minBreakpoint` and `maxBreakpoint`. This allows for better control of which breakpoints can be displayed on smaller devices, rather than forcing all "mobile" layouts into the smallest breakpoint.

**Review by steveruizok — APPROVED** [review]

**Comment by gabrielchl** [comment]
> Worth noting, but I think this would need to be a breaking change. My hope is that whoever this would effect would quickly notice the change!

True, it would be a breaking change anyways so it didn't matter haha. The new solution looks neat!
(sry for the super late reply, I followed this repo and I missed all the updates on this PR amongst the sea of other updates xd)

**Comment by steveruizok** [comment]
Ah I've gone back on some of the design decisions here—`forceMobile` it is!

**Comment by gabrielchl** [comment]
whatttt, either way, yayyy!
yay-icegif-8

**Pull request merged**
