### PR TITLE
Stickies: release candidate

### PR DESCRIPTION
**Pull request by steveruizok**
This PR is the target for the stickies PRs that are moving forward. It should collect changes.

- [x] New icon
- [x] Improved shadows
- [x] Shadow LOD
- [x] New colors / theme options
- [x] Shrink text size to avoid word breaks on the x axis
- [x] Hide indicator whilst typing (reverted)
- [x] Adjacent note positions
  - [x] buttons / clone handles
  - [x] position helpers for creating / translating (pits)
  - [x] keyboard shortcuts: (Tab, Shift+tab (RTL aware), Cmd-Enter, Shift+Cmd+enter)
  - [x] multiple shape translating 
- [x] Text editing
  - [x] Edit on type (feature flagged)
  - [x] click goes in correct place
- [x] Notes as parents (reverted)
- [x] Update colors
- [x] Update SVG appearance

### Change Type

- [x] `sdk` — Changes the tldraw SDK
- [x] `feature` — New feature

### Test Plan

Todo: fold in test plans for child PRs

### Unit tests:

- [ ] Shrink text size to avoid word breaks on the x axis
- [x] Adjacent notes
  - [x] buttons (clone handles)
  - [x] position helpers (pits)
  - [x] keyboard shortcuts: (Tab, Shift+tab (RTL aware), Cmd-Enter, Shift+Cmd+enter)
- [ ] Text editing
  - [ ] Edit on type
  - [ ] click goes in correct place

### Release Notes

- Improves sticky notes (see list)

### CODE REVIEW

**Comment by steveruizok** [comment]
Shadow performance is pretty awful here, might need to walk that back.

**Comment by steveruizok** [comment]
Yeah these shadows are going to be a problem, I think we'll have to pull them out. However, while looking at the problem I also found that there are other performance issues related to opacity: both the .98 opacity on the "body" of the note and the "scrim" which mixes the background color onto the body. If we want fast, we should:
- Remove the scrim and create a separate theme field for sticky note color (and possibly text)
- Remove the .98 opacity on the note (not worth it)
- Remove the 3D shadow on the note (not worth it)

I can see what I can do about creating a cast shadow that approximates what we have in the 3D shadow but we won't be able to get the same look. If it looks bad, we can consider adjustments like sharpening up the note corners.

**Comment by steveruizok** [comment]
Added multiple shape translating pit behavior 

image

**Comment by Taha-Hassan-Git** [comment]
Edge-case behaviour with text overflow:
1. Write a super long word that wraps 4+ lines, and then continue typing
2. Expected: the note should grow to accomodate the new text.
3. Actual: the text overflows the note

Screenshot 2024-04-02 at 11 34 39

[Desktop Mac] Dodgy shadow behaviour:
1. Clone a note shape using alt-drag
2. toggle the alt key
3. Expected: shadows stay the same
4. Actual: shadows change appearance

2024-04-02 at 13 40 04 - Moccasin Kite

[Android Chrome] Shape clones in the wrong position:
1. Keep duplicating by pressing the bottom handle
2. Expected: notes keep cloning in the space below
3. Actual: A note will clone above the original note and off the grid. Sometimes this happens immediately on the first interaction, but sometimes it takes 3-4 attempts. I've not been able to figure out what the trigger is.

https://github.com/tldraw/tldraw/assets/98838967/f23d0c77-3aa7-45e7-a83f-bec514443479

[Andoid Chrome] Handles stuck in hovered state:
1. When duplicating using a handle, put your finger in a position that would overlap the new handle
2. Expected: handle on the new shape is not in hovered state.
3. Actual: handle is in hovered state. And if you continue creating new shapes, that same handle will be hovered each of the new shapes, even if your finger hasn't overlapped the new handle.


https://github.com/tldraw/tldraw/assets/98838967/e3094ff2-7bfb-402b-a1a7-f4eee2f402a6

[ios Safari]
Cloned notes not centered when entering editing state.
1. Create a note and drag it to the bottom of the screen.
2. Duplicate it by pressing the bottom duplicate handle.
3. Expected: Camera should center on the new note in the editing state
4. Actual: Note is behind the keyboard and not visible.

**Comment by steveruizok** [comment]
image

**Comment by steveruizok** [comment]
Multi-translating sticky selection is in

image

**Comment by steveruizok** [comment]
> 1. Clone a note shape using alt-drag
> 2. toggle the alt key
> 3. Expected: shadows stay the same
> 4. Actual: shadows change appearance
> 
> 2024-04-02 at 13 40 04 - Moccasin Kite 

Hm, the shadows are randomized based on the id, I would have thought we kept the shapes/ids around between clones. I think we'd see randomness like this on other draw geo shapes too. Might just be more noticeable here.

**Comment by steveruizok** [comment]
I think I have all the text fixed now. There are some things that we just cannot do on iOS. On mobile (or coarse pointer / touch devices) we won't support "deep selecting" into text shapes. If we can improve this after launch then that's great, otherwise we'll stick with the older behavior on touch devices.

**Comment by steveruizok** [comment]
api docs checks killing me fr

**Comment by steveruizok** [comment]
### Research PRs:
- #3286 
- #3284 
- #3280 
- #3278 
- #3270 
- #3256 
- #3251 
- #3245
- #3224 
- #3219 
- #3222 
- #3216 
- #3213 
- #3212 
- #3208 
- #3206 
- #3204 
- #3202 
- #3164 
- #3162 
- #3157 
- #3152 
- #3145 
- #3143 
- #3142 
- #3134 
- #3133 
- #3104 
- #3102 
- #3100 
- #3098 
- #3097
- #2953

**Pull request merged**
