### PR TITLE
fix: shape parent id on duplicate page

### PR DESCRIPTION
**Pull request by judicaelandria**
Fix shape parent id on duplicated page

### CODE REVIEW

**Comment by judicaelandria** [comment]
closes https://github.com/tldraw/tldraw/issues/531

**Review by steveruizok — DISMISSED** [review]
If a shape is grouped then it should retain its original parent id. This would (I think) flatten all groups and create a bug where a group would still exist without any children pointing back to it.

**Comment by steveruizok** [comment]
The issue is that we base the new page off of app.page (we destructure it at the top of the command), which is always the current page, while we should instead use the pageId argument (
 app.document.pages[pageID]) to get the page that we're duplicating.

**Comment by judicaelandria** [comment]
> If a shape is grouped then it should retain its original parent id. This would (I think) flatten all groups and create a bug where a group would still exist without any children pointing back to it.

The children will always point to the group id but the group parentId will point to the new page id! that should be the expected behavior, right?

**Comment by judicaelandria** [comment]
> The issue is that we base the new page off of app.page (we destructure it at the top of the command), which is always the current page, while we should instead use the pageId argument (
>  app.document.pages[pageID]) to get the page that we're duplicating.

I get your point but it will result the same! i'll change it

**Comment by steveruizok** [comment]
> The children will always point to the group id but the group parentId will point to the new page id! that should be the expected behavior, right?

It's got to be both :( 

This is actually one of the dumb parts of tldraw's data model (to be fixed on the next version!). The parent needs to include the child ID in its children array AND the child needs to have its parent's id (ie the group id) as its parent id.

**Comment by steveruizok** [comment]
> > The issue is that we base the new page off of app.page (we destructure it at the top of the command), which is always the current page, while we should instead use the pageId argument (
> >  app.document.pages[pageID]) to get the page that we're duplicating.
> 
> I get your point but it will result the same! i'll change it

app.page is a shortcut to state.document.pages[currentPageId], so if we're duplicating a different page but accessing app.page then we'll be mixing parts of the duplicating page and the current page. So we need to grab state.document.pages[pageId] instead.

**Pull request merged**
