### PR TITLE
License: add docs

### PR DESCRIPTION
**Pull request by MitjaBezensek**
Do not merge for now - we'll do it when we remove the licensing feature flag.

Adds licensing docs. It also adds a license checker to help people test out their license, if they so desire.

Screenshot 2024-08-01 at 17 00 06

### Change type

- [ ] `bugfix`
- [ ] `improvement`
- [ ] `feature`
- [ ] `api`
- [x] `other`

### Release notes

- Add licensing docs.

### CODE REVIEW

**Comment by mimecuvalo** [comment]
@MitjaBezensek i added a license checker on the Installation page as well. i think maybe we can just land this now! since we have the debug stuff out anyway, it's technically available there, even though it's not completely in the wild yet. we do already have customers getting keys, so let's just push this. can you review the license checker code?

**Comment by MitjaBezensek** [comment]
> @MitjaBezensek i added a license checker on the Installation page as well. i think maybe we can just land this now! since we have the debug stuff out anyway, it's technically available there, even though it's not completely in the wild yet. we do already have customers getting keys, so let's just push this. can you review the license checker code?

Looking good, thanks for adding the license checker 🎉 

I pushed a [small commit](https://github.com/tldraw/tldraw/pull/4217/commits/3c8939052462f63922090af46f55de443b269d3b) to fix some tldraw [version constraint issue](https://github.com/tldraw/tldraw/actions/runs/10202329552/job/28226179066), please double check since it seems you intentionally used `^`.

**Review by mimecuvalo — APPROVED** [review]
LGTM! 🚢

**Comment by mimecuvalo** [comment]
> I pushed a [small commit](https://github.com/tldraw/tldraw/pull/4217/commits/c1f44799408c0c001355e53092bd04f0eeea5c28) to fix some tldraw [version constraint issue](https://github.com/tldraw/tldraw/actions/runs/10202329552/job/28226179066), please double check since it seems you intentionally used ^.

Ah whoops, dunno why I had used that.

**Pull request merged**
