### PR TITLE
stickies: translucency, sometimes

### PR DESCRIPTION
**Pull request by mimecuvalo**
Slight translucency, when not zoomed out. I think maybe the performance hit is worth it — if we're concerned about it, I think we can use a higher breakpoint instead of `editor.getZoomLevel() < 0.35` for these kinds of nicities/LOD. Thoughts?

(argh, I don't know why that api-report keeps changing at the moment - it's just the `NoteShapeUtil.tsx` change)

### CODE REVIEW

**Comment by steveruizok** [comment]
i fucked this PR up

**Comment by steveruizok** [comment]
but I'll land the changes in the stickies rc

**Comment by mimecuvalo** [comment]
woo!

**Comment by mimecuvalo** [comment]
Had to revert - caused blurring on text editing https://linear.app/tldraw/issue/TLD-2380/blurred-text-when-editing

**Pull request closed without merging**
