### PR TITLE
allow className to be passed to tl-canvas

### PR DESCRIPTION
**Pull request by BrianHung**
Allows `className` to be passed as a prop to the `<Canvas/>` element.

### Change Type

- [ ] `patch` — Bug fix
- [x] `minor` — New feature
- [ ] `major` — Breaking change
- [ ] `dependencies` — Changes to package dependencies[^1]
- [ ] `documentation` — Changes to the documentation only[^2]
- [ ] `tests` — Changes to any test code only[^2]
- [ ] `internal` — Any other changes that don't affect the published package[^2]
- [ ] I don't know

[^1]: publishes a `patch` release, for devDependencies use `internal`
[^2]: will not publish a new version

### Test Plan

Should not affect existing behavior.

### Release Notes

- Allows `className` to be passed as a prop to the `<Canvas/>` element

### CODE REVIEW

**Comment by steveruizok** [comment]
Do you need this to be on the Canvas element specifically? With what we have now, you could instead target it by passing a class name to the editor, and then in your CSS target that.

e.g.

```tsx
<TldrawEditor className="my-class"/>
```

```css
.my-class .tl-canvas {
  background-color: red
}
```

**Comment by BrianHung** [comment]
The motivation for the PR was another library needing to add a className to ignore click events, not for styling reasons.
https://github.com/quicktype/glide-data-grid/blob/c9e1f3df5d545171ccca2226c0c55e253fb6cc83/packages/core/src/click-outside-container/click-outside-container.tsx#L23

**Comment by steveruizok** [comment]
This is a little mixed up because I left it stale too long—solving with a different PR that adds this

**Comment by steveruizok** [comment]
https://github.com/tldraw/tldraw/pull/1827

**Pull request closed without merging**
