### PR TITLE
Allow users to drag files from other websites.

### PR DESCRIPTION
**Pull request by MitjaBezensek**
Quick prototype to allow users to drag images from other websites.

It kinda works. There's issues with CORS of course, also the logic for names it not the best (we would just generate a unique name in this case).

### Change Type

- [ ] `patch` — Bug Fix
- [ ] `minor` — New Feature
- [ ] `major` — Breaking Change
- [ ] `dependencies` — Dependency Update (publishes a `patch` release, for devDependencies use `internal`)
- [ ] `documentation` — Changes to the documentation only (will not publish a new version)
- [ ] `tests` — Changes to any testing-related code only (will not publish a new version)
- [ ] `internal` — Any other changes that don't affect the published package (will not publish a new version)

### Test Plan

1. Add a step-by-step description of how to test your PR here.
2.

- [ ] Unit Tests
- [ ] Webdriver tests

### Release Notes

- Add a brief release note for your PR here.

### CODE REVIEW

**Comment by steveruizok** [comment]
What's the status of this one? I'd like to have this feature, does it still need work?

**Comment by MitjaBezensek** [comment]
I think we would need to fetch images server side. Fetching from the browser runs into CORS issues
https://stackoverflow.com/a/25431481/1810018

**Comment by steveruizok** [comment]
Interesting, I bet we could do that on tldraw.com at least.

**Comment by MitjaBezensek** [comment]
Will take a look how it was done there 👍

**Comment by MitjaBezensek** [comment]
Closing this one in favor of https://github.com/tldraw/brivate/pull/1973

**Pull request closed without merging**
