### PR TITLE
images: dont stop playing a gif on double click

### PR DESCRIPTION
**Pull request by mimecuvalo**
Double-clicking currently pauses gif's which is odd. This changes is so that you can unpause them (if they were stopped for reduced motion reasons). But they can't be paused.

### Change type

- [ ] `bugfix`
- [x] `improvement`
- [ ] `feature`
- [ ] `api`
- [ ] `other`

### Release notes

- Images: dbl-clicking doesn't stop gifs

### CODE REVIEW

**Comment by ds300** [comment]
related: #4358

**Review by steveruizok — APPROVED** [review]

**Comment by steveruizok** [comment]
Works for me. We could probably cut deeper and remove the rest of the double click functionality? Or are you planning to pull that in a different PR?

**Comment by mimecuvalo** [comment]
> We could probably cut deeper and remove the rest of the double click functionality? Or are you planning to pull that in a different PR?

I think we still need a way to play the gif though if it's initially paused (thru the reduced-motion setting).
Or do you mean removing the cropping behavior for gifs? I know in https://github.com/tldraw/tldraw/issues/4358 it was maybe suggesting that we drop cropping for gifs but I'm not entirely convinced.

**Comment by steveruizok** [comment]
Easier done than said, so I've pushed a change that removes the "double click to toggle isPlaying".

**Pull request merged**
