### PR TITLE
editing: stay in edit mode across shape editing

### PR DESCRIPTION
**Pull request by mimecuvalo**
This is what we were talking about offline about staying in flow when already in edit mode!

This PR is stacked on top of https://github.com/tldraw/tldraw/pull/3132

I'll add tests after we decide that this is the right direction we want to go in.

https://github.com/tldraw/tldraw/assets/469604/86f42c4e-e2a3-463f-bbd5-42c51c36e0e4

### Change Type

- [x] `sdk` — Changes the tldraw SDK
- [ ] `dotcom` — Changes the tldraw.com web app
- [ ] `docs` — Changes to the documentation, examples, or templates.
- [ ] `vs code` — Changes to the vscode plugin
- [ ] `internal` — Does not affect user-facing stuff

- [ ] `bugfix` — Bug fix
- [ ] `feature` — New feature
- [x] `improvement` — Improving existing features
- [ ] `chore` — Updating dependencies, other boring stuff
- [ ] `galaxy brain` — Architectural changes
- [ ] `tests` — Changes to any test code
- [ ] `tools` — Changes to infrastructure, CI, internal scripts, debugging tools, etc.
- [ ] `dunno` — I don't know

### Test Plan

1. Add a step-by-step description of how to test your PR here.
2.

- [ ] Unit Tests
- [ ] End to end tests

### Release Notes

- Editing: stay in edit mode if you were already in an editing state.

### CODE REVIEW

**Comment by mimecuvalo** [comment]
This PR is no longer stacked on top of https://github.com/tldraw/tldraw/pull/3132 because I was asked to start unstack things. So, this preview deployment doesn't work at the moment until that other stuff lands.

**Comment by mimecuvalo** [comment]
(nvm, I read it wrong - this one should stay stacked)

**Comment by TodePond** [comment]
The behaviour of this PR appears to be different to what's shown in the gif. Is that because of a decided change, or is it slightly buggy at the moment?

**Comment by mimecuvalo** [comment]
> The behaviour of this PR appears to be different to what's shown in the gif. Is that because of a decided change, or is it slightly buggy at the moment?

ach! my bad, i didn't sync up with the base PR - synced up now and a new deploy is going out 👍

**Pull request merged**
