### PR TITLE
Add IDs to UI components

### LINKED ISSUE #503: [feature] Add IDs to UI elements to make them easy to override
Adding IDs to the UI elements like the menu tabs will make it easier to style/remove them. This is useful as my application uses TLDraw but wants to disable some of the features from the menu.

### PR DESCRIPTION
**Pull request by FarazzShaikh**
Add IDs to the following
- [x] Burger Menu
- [x] Style menu
- [x] Toolbar
- [x] Context menu

@steveruizok How is this manual approach for now? I could swear I had seen a library that can auto assign IDs based on the component name but I forgot its name. Do you know of any such library?

Closes #503

### CODE REVIEW

**Comment by FarazzShaikh** [comment]
This is ready @steveruizok 

(Tag cause I can't assign reviewers for some reason)

**Comment by steveruizok** [comment]
Thanks!

**Comment by steveruizok** [comment]
Small note: remember that there may be more than once instance of a <Tldraw> component on a page, which will lead to duplicate IDs. This is pretty obscure and wouldn't break anything.

**Comment by FarazzShaikh** [comment]
Yeah this ID thing is just a temporary fix until we develop more modular UI.

**Pull request merged**
