### PR TITLE
[experiment] Allow adding of classnames to shapes.

### PR DESCRIPTION
**Pull request by MitjaBezensek**
What if? 😄 

### Change type

- [ ] `bugfix`
- [ ] `improvement`
- [ ] `feature`
- [ ] `api`
- [ ] `other`

### Test plan

1. Create a shape...
2.

- [ ] Unit tests
- [ ] End to end tests

### Release notes

- Fixed a bug with…

### CODE REVIEW

**Comment by Taha-Hassan-Git** [comment]
holy dang!

**Comment by mimecuvalo** [comment]
dude. yes.

**Comment by steveruizok** [comment]
nooo

**Comment by MitjaBezensek** [comment]
Ok, closing this then 😂

**Pull request closed without merging**
