### PR TITLE
Interpolation: draw/highlight points, discrete props

### PR DESCRIPTION
**Pull request by Taha-Hassan-Git**
Draw shapes and highlighter shape points now animate between states.

2024-07-22 at 13 44 45 - Teal Sparrow

There is some repetition of logic between the function that animates draw points and the one that animates lines. However, I felt that the structure of draw shapes and lines is different enough that generalising the function would add complexity and sacrifice readability, and didn't seem worth it just to remove a small amount of repetition. Very happy to change that should anyone disagree.

Image shape crop property animates to the new position

2024-07-22 at 15 39 30 - Purple Cattle

Discrete props (props that don't have continuous values to animate along) now change in the middle of the animation. It's likely that continuous animation will be happening at the same time, making the change in the middle of that movement helps smooth over the abruptness of that change.

This is what it looks like if they change at the start:

2024-07-18 at 13 11 32 - Amaranth Primate

This is what it looks like when the props change halfway:

2024-07-18 at 13 12 40 - Teal Gerbil

The text usually changes at the halfway mark, but if there's no text to begin with, then any text in the end shape is streamed in:

2024-07-18 at 15 18 34 - Tan Catshark

Question: Do we want tests for this?

### Change type

- [ ] `bugfix`
- [x] `improvement`
- [ ] `feature`
- [x] `api`
- [ ] `other`

### Test plan

1. Animate a shape between different states
2. It should change its discrete props at the midway point of the animation, and animate smoothly for continuous values such as dimension or position.

### Release notes

- Added getInterpolated props method for all shapes, including draw and highlighter.

### CODE REVIEW

**Comment by Taha-Hassan-Git** [comment]
> half tempted to try and port this old draw line interpolation code here: Kapture 2024-07-22 at 17 34 08 [ Kapture 2024-07-22 at 17 34 08 ](https://private-user-images.githubusercontent.com/1489520/351044450-7c148178-993e-45bc-986d-a2c791090774.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3MjMxNDEsIm5iZiI6MTcyMTcyMjg0MSwicGF0aCI6Ii8xNDg5NTIwLzM1MTA0NDQ1MC03YzE0ODE3OC05OTNlLTQ1YmMtOTg2ZC1hMmM3OTEwOTA3NzQuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjNUMDgyMDQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGM4YjA5ZjIwZmY0M2Y0ZDJmYjg0ODgwMzZlMzE2N2FkYmFhMGUyNDI5ZWJkNWYxZmE1NTJmODFiM2E1ZmU2MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.a5MV8_0mz41XuO0bhtQnBff_gvSqAysl0KxHETA1i48) [ ](https://private-user-images.githubusercontent.com/1489520/351044450-7c148178-993e-45bc-986d-a2c791090774.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3MjMxNDEsIm5iZiI6MTcyMTcyMjg0MSwicGF0aCI6Ii8xNDg5NTIwLzM1MTA0NDQ1MC03YzE0ODE3OC05OTNlLTQ1YmMtOTg2ZC1hMmM3OTEwOTA3NzQuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjNUMDgyMDQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGM4YjA5ZjIwZmY0M2Y0ZDJmYjg0ODgwMzZlMzE2N2FkYmFhMGUyNDI5ZWJkNWYxZmE1NTJmODFiM2E1ZmU2MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.a5MV8_0mz41XuO0bhtQnBff_gvSqAysl0KxHETA1i48)

This is great! Where is it? You should for sure do it if you have time.

**Comment by steveruizok** [comment]
The draw shape interpolation works pretty well! I was curious how the segments would get handled but this is pretty acceptable.

Kapture 2024-08-02 at 16 35 10
Kapture 2024-08-02 at 16 35 101

**Comment by steveruizok** [comment]
Yet another reason I wish we rotated from center, holy shit
Kapture 2024-08-02 at 16 44 32

**Comment by steveruizok** [comment]
Another general animation issue that we'd have to fix: animating to another parent.

Kapture 2024-08-02 at 16 46 19

**Comment by steveruizok** [comment]
Streaming in text for note shapes is cursed due to the font size adjustment, dropping it for note shapes.

Kapture 2024-08-02 at 16 47 41

**Comment by steveruizok** [comment]
The `interpolateDiscrete` function seems unnecessary. If we're doing that as the default, then we can spread one or the other props based on progress.

```ts
override getInterpolatedProps(
	startShape: TLFrameShape,
	endShape: TLFrameShape,
	t: number
): TLFrameShapeProps {
	return {
		...(t > 0.5 ? endShape.props : startShape.props),
		w: lerp(startShape.props.w, endShape.props.w, t),
		h: lerp(startShape.props.h, endShape.props.h, t),
	}
}
```

I am concerned about animating width and height for shapes with a `growY`, as this will look pretty weird.

**Comment by steveruizok** [comment]
Yeah growY is going to be tricky here.

Kapture 2024-08-02 at 18 38 13

**Comment by steveruizok** [comment]
Ok, plenty more to do but I think this is good to land.

**Pull request merged**
