### PR TITLE
text: fix a text measurement edge case in rendering in Chrome.

### PR DESCRIPTION
**Pull request by mimecuvalo**
See the attached issue https://github.com/tldraw/tldraw/issues/4804

### Change type

- [x] `bugfix`
- [ ] `improvement`
- [ ] `feature`
- [ ] `api`
- [ ] `other`

### Release notes

- Fix a text measurement edge case in rendering in Chrome.

### CODE REVIEW

**Comment by mimecuvalo** [comment]
@steveruizok pushed up an alternate fix which isn't pretty either but lemme know what you think

**Comment by mimecuvalo** [comment]
I looked into this more and the root of this problem is actually more tied to the Draw font. The problem seems to be the slightly random variation in the font in some renders.

This is an issue we've seen before with this font, where it doesn't always consistently produce the same output.

**Comment by steveruizok** [comment]
> I looked into this more and the root of this problem is actually more tied to the Draw font. The problem seems to be the slightly random variation in the font in some renders.
> 
> This is an issue we've seen before with this font, where it doesn't always consistently produce the same output.

I think I replied on a different thread, but let's see if we can either turn off the randomization or create a fork of the font that is deterministic. Still worried that this will be moving the problem around rather...

**Comment by mimecuvalo** [comment]
for record keeping here: @ds300 is working on recompiling the font in general. (which will also remove the randomization here)

**Pull request closed without merging**
